### ISSUE TITLE
Youtube downloading doesn't work

### ISSUE THREAD

**Issue by bzzrak** [MilesChing/ThunderX#75]
Hi, downloading videos from youtube isn't working for me. When I paste an URL into the box, nothing happens. The small progress bar under the box runs for a few seconds, then... nothing.

**Comment by MilesChing** [comment]
Thanks for reporting. Is this the first time you try to download from YouTube? Sometimes YouTube may block your IP because of the frequency of requests. It could also be due to some problems with the library we're using, I'm going to check this later.

Another suggestion is to check if Thunder X is granted network permissions in your desktop settings.

**Comment by bzzrak** [comment]
I bought the app yesterday, so yeah first time, I really like it so far btw :)
Just tried it with a VPN, no luck. Torrent/magnet files work fine.

**Comment by MilesChing** [comment]
Exception caught analyzing video https://www.youtube.com/watch?v=gy480NqX7yU

```
Failed to perform an HTTP request to YouTube due to a fatal failure.
In most cases, this error indicates that YouTube most likely changed something, which broke the library.
If this issue persists, please report it on the project's GitHub page.

Method: GET, RequestUri: 'https://www.youtube.com/get_video_info?video_id=gy480NqX7yU&el=embedded&eurl=https://youtube.googleapis.com/v/gy480NqX7yU&hl=en&sts=', Version: 2.0, Content: <null>, Headers:
{
  User-Agent: Mozilla/5.0
  User-Agent: (Windows NT 10.0; Win64; x64)
  User-Agent: AppleWebKit/537.36
  User-Agent: (KHTML, like Gecko)
  User-Agent: Chrome/86.0.4240.111
  User-Agent: Safari/537.36
  Accept-Encoding: gzip
  Accept-Encoding: deflate
}

StatusCode: 404, ReasonPhrase: '', Version: 2.0, Content: System.Net.Http.StreamContent, Headers:
{
  Server: YouTube
  Server: Frontend
  Server: Proxy
  Strict-Transport-Security: max-age=31536000
  Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-T051=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
  Cache-Control: no-cache
  Date: Tue, 15 Jun 2021 06:19:15 GMT
  X-Frame-Options: SAMEORIGIN
  X-Content-Type-Options: nosniff
  x-xss-protection: 0
  Content-Length: 0
  Content-Type: text/html; charset=utf-8
  Expires: Tue, 27 Apr 1971 19:44:06 GMT
}
```

This is probably caused by the same reason as described in https://github.com/Tyrrrz/YoutubeExplode/issues/548. I'm going to upgrade our dependency of [YoutubeExplode](https://github.com/Tyrrrz/YoutubeExplode) to the latest version and check if this still happens.
